### ISSUE TITLE
Integrate affine transformation

### ISSUE THREAD

**Issue by cong-code** [cwmok/C2FViT#10]
Hi, how to integrate multiple affine parameters obtained from coarse-to-fine registration into one finnal affine parameter?

**Comment by cwmok** [comment]
Hi @cong-code,

In short, we don't integrate multiple affine parameters. We found that it is the best to simply use the affine parameters from the final stage (the finest resolution).

**Comment by cong-code** [comment]
Thank you for your reply. If I want to integrate multiple affine transformations, should I add them directly as the final result?

**Comment by cwmok** [comment]
No, you should do the affine matrix multiplication instead of addition.

**Comment by cong-code** [comment]
Understand, does the affine matrix refer to the 3X4 transformation matrix? Shall I directly use the one-dimensional vector output by the final model for multiplication?

**Comment by cwmok** [comment]
Yes, the affine matrix is the 3x4 transformation. You have to pad it to 4x4 in order to do the matrix multiplication.

**Comment by cong-code** [comment]
Thanks !
