### ISSUE TITLE
Can we use the affine augmentation params as train supervision

### ISSUE THREAD

**Issue by Zhenghao97** [cwmok/C2FViT#13]
Hi, thanks for your impressing work~

If the moving image is obtained by data augmentation, does that mean we have the groundtruth label of the affine params?

So can we leverage the supervision of affine params during training phase, such as l1 loss?

Looking forward for your reply, appreciate it~

**Comment by cwmok** [comment]
Hi @Zhenghao97,

>>If the moving image is obtained by data augmentation, does that mean we have the groundtruth label of the affine params?


Yes, it will work for the intra-subject registration task where the images are pre-aligned after image acquisition. But in our paper, we focus on inter-subject registration or atlas-based registration, in which the groundtruth affine transformation of the dataset doesn't exist. Therefore, we will need a similarity measure to supervise the training.

Thanks for your interest in our work!
