### ISSUE TITLE
Downsample image before feeding into network

### ISSUE THREAD

**Issue by GrigoriPlatonov** [cwmok/C2FViT#14]
Thanks for your great work!

I have a question about the code. I notice that you use the half resolution image(128*128*128) to feed into the model to predict the affine matrix for original size image(256*256*256). However in the paper, you said highest resolution of the image pyramid should be the same with input image.
Can you explain this to me? Thanks!

**Comment by cwmok** [comment]
Hi @GrigoriPlatonov,

We use half-resolution input for the network. This will significantly accelerate the training process without sacrificing registration accuracy. Yet, the evaluation is conducted with images with original size (256 x 256 x 256). 

>> However, in the paper, you said the highest resolution of the image pyramid should be the same as the input image.

Yes, here, the input image refers to the half-resolution input.
