### ISSUE TITLE
Example data in the paper requires

### ISSUE THREAD

**Issue by CrimsonLeev** [cwmok/C2FViT#15]
Your work inspired me a lot. Thanks for your work. And, can you upload these two example images from the paper? I need them to test my own network and make a comparison table. 
Thanks a lot.
![IMG_0189](https://github.com/cwmok/C2FViT/assets/87789180/57279e57-076d-4d76-846e-4e78bcbdd263)

**Comment by cwmok** [comment]
Hi @CrimsonLeev,

I am afraid I cannot provide the required data as I will no longer be able to access my lab computer at my university. 
This example data is randomly selected from the dataset (https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md). I hope this will help.

**Comment by CrimsonLeev** [comment]
> Hi @CrimsonLeev,
> 
> I am afraid I cannot provide the required data as I will no longer be able to access my lab computer at my university. This example data is randomly selected from the dataset (https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md). I hope this will help.

Thanks, I have found them.
