### ISSUE TITLE
2Dmedical images

### ISSUE THREAD

**Issue by JAYCHOU2020** [cwmok/C2FViT#8]
Thanks for your excellent work. Can this method be used for registration of 2d medical images?

**Comment by cwmok** [comment]
Hi @JAYCHOU2020,

Thanks for your interest in our work.

Currently, I don't have any plan to extend this repo into 2D. Affine registration in 2D is computationally tractable for convex optimization/multi-start procedure (see [here](https://github.com/stnava/butterfly)). You can basically compute the optimal solutions without any learning/CNN/ViT. A detailed discussion about 2D registration is available here: https://github.com/cwmok/C2FViT/issues/4
